begin;

drop table if exists conversations;

create table chats (
    id          bigint generated by default as identity primary key,
    session_id  varchar(255) not null,
    tenant_id   uuid references tenants(id) on delete cascade,
    role        varchar(20),
    message     jsonb not null,
    created_at  timestamptz not null default current_timestamp
);

create index idx_chats_session_id on chats(session_id);
create index idx_chats_tenant_id on chats(tenant_id);

commit;
