begin;

create table human_takeovers (
    id          bigint generated by default as identity primary key,
    session_id  varchar(255) not null,
    tenant_id   uuid not null references tenants(id) on delete cascade,
    paused_by   uuid references users(id) on delete set null,
    paused_at   timestamptz not null default now(),
    expires_at  timestamptz not null,
    released_at timestamptz,
    active      boolean not null default true
);

create unique index uq_active_takeover on human_takeovers(session_id) where active = true;
create index idx_human_takeovers_session on human_takeovers(session_id);
create index idx_human_takeovers_tenant on human_takeovers(tenant_id);

commit;
