begin;

create table cart_sessions (
    id          bigint generated by default as identity primary key,
    session_id  varchar(255) not null,
    tenant_id   uuid not null references tenants(id) on delete cascade,
    last_active timestamptz not null default now(),
    has_order   boolean not null default false,
    recovered   boolean not null default false,
    created_at  timestamptz not null default now()
);

create index idx_cart_sessions_pending on cart_sessions(session_id, has_order) where has_order = false;

commit;
