begin;

alter table users add column password_hash text;
alter table users add column last_login timestamptz;

create table session_tokens (
    id          bigint generated by default as identity primary key,
    user_id     uuid not null references users(id) on delete cascade,
    token       text not null unique,
    expires_at  timestamptz not null,
    created_at  timestamptz not null default now()
);
create index idx_session_tokens_token on session_tokens(token);
create index idx_session_tokens_user on session_tokens(user_id);

commit;
