begin;

insert into global_products (name, description, category) values
-- ═══ HAMBÚRGUERES ═══
('X-Salada', 'Hambúrguer com queijo, alface, tomate e maionese', 'Hambúrgueres'),
('X-Bacon', 'Hambúrguer com queijo, bacon crocante, alface e tomate', 'Hambúrgueres'),
('X-Tudo', 'Hambúrguer com queijo, bacon, ovo, presunto, alface, tomate e maionese', 'Hambúrgueres'),
('X-Egg', 'Hambúrguer com queijo e ovo frito', 'Hambúrgueres'),
('X-Burger', 'Hambúrguer clássico com queijo e molho especial', 'Hambúrgueres'),
('X-Frango', 'Filé de frango empanado com queijo e salada', 'Hambúrgueres'),
('X-Coração', 'Hambúrguer com queijo, bacon, ovo, cheddar e onion rings', 'Hambúrgueres'),
('X-Cheddar', 'Hambúrguer com duplo cheddar e bacon', 'Hambúrgueres'),
('X-Calabresa', 'Hambúrguer com queijo e calabresa acebolada', 'Hambúrgueres'),
('X-Milho', 'Hambúrguer com queijo e milho verde', 'Hambúrgueres'),
('X-Burger Duplo', 'Dois hambúrgueres com queijo, alface, tomate e maionese', 'Hambúrgueres'),
('X-Salada Duplo', 'Dois hambúrgueres com queijo, alface, tomate, cebola roxa e maionese', 'Hambúrgueres'),
('Smash Burger', 'Hambúrguer smash com queijo cheddar, cebola caramelizada e molho especial', 'Hambúrgueres'),
('Smash Duplo', 'Dois smash burgers com cheddar, bacon e molho especial', 'Hambúrgueres'),
('Costela Burger', 'Hambúrguer de costela com queijo provolone e cebola crispy', 'Hambúrgueres'),
('Veggie Burger', 'Hambúrguer de grão de bico com queijo, alface, tomate e molho tahine', 'Hambúrgueres'),
('Rústico Burger', 'Hambúrguer artesanal com queijo brie, geleia de pimenta e rúcula', 'Hambúrgueres'),
('BBQ Burger', 'Hambúrguer com queijo, bacon, onion rings e molho barbecue', 'Hambúrgueres'),
('Tríplo Burger', 'Três hambúrgueres com triplo queijo e molho especial', 'Hambúrgueres'),
('Hot Dog Simples', 'Salsicha com purê, vinagrete, batata palha e ketchup/mostarda', 'Hambúrgueres'),
('Hot Dog Completo', 'Salsicha dupla com purê, vinagrete, batata palha, milho, queijo ralado e maionese', 'Hambúrgueres'),
('Hot Dog Cheddar', 'Salsicha com cheddar cremoso e bacon', 'Hambúrgueres'),
('Hot Dog Calabresa', 'Salsicha com calabresa acebolada e queijo', 'Hambúrgueres'),
('Misto Quente', 'Pão de hot dog com presunto e queijo derretido', 'Hambúrgueres'),

-- ═══ ACOMPANHAMENTOS ═══
('Batata Frita Pequena', 'Porção pequena de batata frita crocante (200g)', 'Acompanhamentos'),
('Batata Frita Média', 'Porção média de batata frita crocante (300g)', 'Acompanhamentos'),
('Batata Frita Grande', 'Porção grande de batata frita crocante (500g)', 'Acompanhamentos'),
('Batata com Cheddar e Bacon', 'Batata frita com cheddar cremoso e bacon', 'Acompanhamentos'),
('Batata Rústica', 'Batata rústica com alecrim e alho', 'Acompanhamentos'),
('Onion Rings', 'Anéis de cebola empanados e fritos', 'Acompanhamentos'),
('Nachos com Cheddar', 'Nachos crocantes com cheddar cremoso e jalapeño', 'Acompanhamentos'),
('Polenta Frita', 'Palitos de polenta crocante', 'Acompanhamentos'),

-- ═══ PORÇÕES ═══
('Porção de Batata Frita', 'Porção grande para compartilhar (600g)', 'Porções'),
('Porção de Onion Rings', 'Anéis de cebola para compartilhar', 'Porções'),
('Porção de Nuggets', 'Nuggets de frango com molho (12 unidades)', 'Porções'),
('Porção de Calabresa', 'Calabresa acebolada com queijo', 'Porções'),
('Porção de Frango à Passarinho', 'Frango frito temperado com limão', 'Porções'),
('Porção de Mandioca Frita', 'Mandioca frita crocante com molho verde', 'Porções'),
('Porção de Isca de Frango', 'Iscas de frango empanadas com molho ranch', 'Porções'),
('Porção de Bolinho de Aipim', 'Bolinhos de aipim com queijo (8 unidades)', 'Porções'),
('Porção de Bolinho de Bacalhau', 'Bolinhos de bacalhau (6 unidades)', 'Porções'),
('Porção de Torresmo', 'Torresmo crocante com limão', 'Porções'),
('Porção Mista', 'Batata frita, nuggets e onion rings', 'Porções'),
('Porção de Aipim com Cheddar', 'Aipim frito com cheddar e bacon', 'Porções'),

-- ═══ BEBIDAS ═══
('Coca-Cola 350ml', 'Lata de Coca-Cola 350ml', 'Bebidas'),
('Coca-Cola 600ml', 'Garrafa de Coca-Cola 600ml', 'Bebidas'),
('Coca-Cola Zero 350ml', 'Lata de Coca-Cola Zero 350ml', 'Bebidas'),
('Guaraná Antarctica 350ml', 'Lata de Guaraná Antarctica 350ml', 'Bebidas'),
('Guaraná Antarctica 600ml', 'Garrafa de Guaraná Antarctica 600ml', 'Bebidas'),
('Fanta Laranja 350ml', 'Lata de Fanta Laranja 350ml', 'Bebidas'),
('Fanta Uva 350ml', 'Lata de Fanta Uva 350ml', 'Bebidas'),
('Sprite 350ml', 'Lata de Sprite 350ml', 'Bebidas'),
('Kuat 350ml', 'Lata de Kuat 350ml', 'Bebidas'),
('Schweppes Citrus 350ml', 'Lata de Schweppes Citrus 350ml', 'Bebidas'),
('Pepsi 350ml', 'Lata de Pepsi 350ml', 'Bebidas'),
('Água Mineral 500ml', 'Água mineral sem gás 500ml', 'Bebidas'),
('Água Mineral com Gás 500ml', 'Água mineral com gás 500ml', 'Bebidas'),
('Suco de Laranja 400ml', 'Suco de laranja natural 400ml', 'Bebidas'),
('Suco de Limão 400ml', 'Suco de limão com hortelã 400ml', 'Bebidas'),
('Suco de Maracujá 400ml', 'Suco de maracujá 400ml', 'Bebidas'),
('Suco de Abacaxi 400ml', 'Suco de abacaxi com hortelã 400ml', 'Bebidas'),
('Suco de Morango 400ml', 'Suco de morango 400ml', 'Bebidas'),
('Chá Gelado de Pêssego 450ml', 'Chá gelado sabor pêssego', 'Bebidas'),
('Chá Gelado de Limão 450ml', 'Chá gelado sabor limão', 'Bebidas'),
('Milk-Shake Chocolate 400ml', 'Milk-shake de chocolate com chantilly', 'Bebidas'),
('Milk-Shake Morango 400ml', 'Milk-shake de morango com chantilly', 'Bebidas'),
('Milk-Shake Ovomaltine 400ml', 'Milk-shake de Ovomaltine com chantilly', 'Bebidas'),
('Vitamina de Banana 400ml', 'Vitamina de banana com leite', 'Bebidas'),

-- ═══ CERVEJAS ═══
('Cerveja Heineken 350ml', 'Long neck Heineken 350ml', 'Cervejas'),
('Cerveja Heineken 600ml', 'Garrafa Heineken 600ml', 'Cervejas'),
('Cerveja Brahma 350ml', 'Lata de Brahma 350ml', 'Cervejas'),
('Cerveja Brahma 600ml', 'Garrafa de Brahma 600ml', 'Cervejas'),
('Cerveja Skol 350ml', 'Lata de Skol 350ml', 'Cervejas'),
('Cerveja Skol 600ml', 'Garrafa de Skol 600ml', 'Cervejas'),
('Cerveja Antarctica 350ml', 'Lata de Antarctica 350ml', 'Cervejas'),
('Cerveja Budweiser 350ml', 'Long neck Budweiser 350ml', 'Cervejas'),
('Cerveja Corona 330ml', 'Long neck Corona 330ml', 'Cervejas'),
('Cerveja Stella Artois 330ml', 'Long neck Stella Artois 330ml', 'Cervejas'),
('Cerveja Amstel 350ml', 'Lata de Amstel 350ml', 'Cervejas'),
('Cerveja Original 350ml', 'Lata de Original 350ml', 'Cervejas'),

-- ═══ SOBREMESAS ═══
('Sundae Chocolate', 'Sundae de chocolate com cobertura e granulado', 'Sobremesas'),
('Sundae Morango', 'Sundae de morango com cobertura', 'Sobremesas'),
('Sundae Caramelo', 'Sundae de caramelo com cobertura', 'Sobremesas'),
('Brownie com Sorvete', 'Brownie de chocolate com sorvete de baunilha e calda', 'Sobremesas'),
('Petit Gâteau', 'Bolo de chocolate com interior cremoso e sorvete', 'Sobremesas'),
('Torta de Limão', 'Fatia de torta de limão com merengue', 'Sobremesas'),
('Torta de Chocolate', 'Fatia de torta de chocolate', 'Sobremesas'),
('Churros com Doce de Leite', 'Churros recheados com doce de leite (4 unidades)', 'Sobremesas'),
('Mini Churros Canela', 'Mini churros com açúcar e canela (6 unidades)', 'Sobremesas'),
('Açaí 300ml', 'Açaí com banana, granola e leite condensado', 'Sobremesas'),
('Açaí 500ml', 'Açaí com banana, granola, leite condensado e morango', 'Sobremesas'),
('Milk-Shake Ovomaltine Sobremesa', 'Milk-shake espesso de Ovomaltine com chantilly e calda', 'Sobremesas'),

-- ═══ ADICIONAIS / EXTRAS ═══
('Extra Bacon', 'Porção extra de bacon crocante', 'Adicionais'),
('Extra Queijo', 'Porção extra de queijo', 'Adicionais'),
('Extra Ovo', 'Ovo frito adicional', 'Adicionais'),
('Extra Hambúrguer', 'Hambúrguer adicional', 'Adicionais'),
('Extra Calabresa', 'Porção extra de calabresa', 'Adicionais'),
('Extra Cheddar', 'Porção extra de cheddar', 'Adicionais'),
('Extra Onion Rings', 'Onion rings adicionais (3 unidades)', 'Adicionais'),
('Extra Milho', 'Milho verde adicional', 'Adicionais'),
('Extra Presunto', 'Fatia extra de presunto', 'Adicionais'),

-- ═══ MOLHOS ═══
('Molho Barbecue', 'Molho barbecue defumado', 'Molhos'),
('Molho Cheddar', 'Molho cheddar cremoso', 'Molhos'),
('Molho Ranch', 'Molho ranch com ervas', 'Molhos'),
('Molho Picante', 'Molho hot sauce picante', 'Molhos'),
('Molho Tártaro', 'Molho tártaro com picles', 'Molhos'),
('Molho Especial da Casa', 'Molho secreto do chef', 'Molhos'),
('Ketchup Extra', 'Pote de ketchup', 'Molhos'),
('Mostarda Extra', 'Pote de mostarda', 'Molhos'),
('Maionese Extra', 'Pote de maionese', 'Molhos'),

-- ═══ COMBOS ═══
('Combo 1 - X-Salada + Batata P + Refri', 'X-Salada com batata frita pequena e refrigerante 350ml', 'Combos'),
('Combo 2 - X-Bacon + Batata M + Refri', 'X-Bacon com batata frita média e refrigerante 600ml', 'Combos'),
('Combo 3 - X-Tudo + Batata G + Refri', 'X-Tudo com batata frita grande e refrigerante 600ml', 'Combos'),
('Combo Kids - X-Burger + Batata P + Suco', 'X-Burger simples com batata pequena e suco', 'Combos'),
('Combo Casal - 2 X-Salada + Batata G + 2 Refri', 'Dois X-Salada com batata grande e dois refrigerantes', 'Combos'),
('Combo Família - 3 X-Tudo + 2 Batata G + 3 Refri', 'Três X-Tudo com duas batatas grandes e três refrigerantes', 'Combos'),
('Combo Smash - Smash Duplo + Batata M + Refri', 'Smash Duplo com batata média e refrigerante 600ml', 'Combos'),
('Combo BBQ - BBQ Burger + Onion Rings + Refri', 'BBQ Burger com onion rings e refrigerante 600ml', 'Combos'),

-- ═══ PASTÉIS ═══
('Pastel de Queijo', 'Pastel crocante recheado com queijo', 'Pastéis'),
('Pastel de Carne', 'Pastel crocante recheado com carne moída temperada', 'Pastéis'),
('Pastel de Frango', 'Pastel crocante recheado com frango desfiado', 'Pastéis'),
('Pastel de Pizza', 'Pastel recheado com mussarela, tomate e orégano', 'Pastéis'),
('Pastel de Calabresa', 'Pastel recheado com calabresa e queijo', 'Pastéis'),
('Pastel de Palmito', 'Pastel recheado com palmito e queijo', 'Pastéis'),
('Pastel de Camarão', 'Pastel recheado com camarão e catupiry', 'Pastéis'),
('Pastel Doce de Chocolate', 'Pastel doce recheado com chocolate', 'Pastéis'),
('Pastel Doce de Guava', 'Pastel doce recheado com goiabada e queijo', 'Pastéis');

commit;
